export const GET_COURSE_CATEGORIES = "GET_COURSE_CATEGORIES";
export const GET_COURSE_BY_CATEGORY = "GET_COURSE_BY_CATEGORY";
export const GET_COURSE_BY_CATEGORY_ERR = "GET_COURSE_BY_CATEGORY_ERR";
export const GET_COURSE_LIST = "GET_COURSE_LIST";
export const GET_CART_COURSE = "GET_CART_COURSE";
export const GET_USER_AUTH_LOGIN_INFO = "GET_USER_AUTH_LOGIN_INFO";
export const CREATE_NOTI_OBJ = "CREATE_NOTI_OBJ";
export const GET_COURSE_INFO = "GET_COURSE_INFO";
